services:
  ros2_lyrical:
    build:
      context: .
      # target: base  # <--- THIS IS FOR ONLY BASE
      target: desktop # <--- THIS IS FOR DESKTOP
      args:
        # Single point of control for ROS_DISTRO (default: lyrical)
        - ROS_DISTRO=${ROS_DISTRO:-lyrical}
    container_name: ${ROS_DISTRO:-lyrical}_dev
    network_mode: host
    ipc: host

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu, graphics, utility, display ]

    environment:
      - DISPLAY=${DISPLAY}
      - WAYLAND_DISPLAY=${WAYLAND_DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - __NV_PRIME_RENDER_OFFLOAD=1
      - __GLX_VENDOR_LIBRARY_NAME=nvidia
      - LIBGL_ALWAYS_SOFTWARE=0
      - LIBGL_ALWAYS_INDIRECT=0
      - OGRE_RTT_MODE=Copy
      - __GL_THREADED_OPTIMIZATIONS=0
      - __GL_SYNC_TO_VBLANK=1
      - QT_ENABLE_HIGHDPI_SCALING=0
      - QT_AUTO_SCREEN_SCALE_FACTOR=0
      - QT_SCALE_FACTOR=1
      - XDG_RUNTIME_DIR=/tmp/runtime-root
      # Force ROS 2 logging engines to maintain full color output inside the container
      - RCUTILS_COLORIZED_OUTPUT=1

    volumes:
      # Use ../ to go up one level from the 'docker' folder to 'ros2_ws'
      - ../ros2_ws/:/root/ros2_ws/
      # The Bridge for GUI data
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # Pass Wayland socket if present on host
      - /run/user/1000:/run/user/1000:rw
      # Add this to allow access to the direct rendering manager
      - /dev/dri:/dev/dri:rw

    stdin_open: true
    tty: true
    privileged: true
    working_dir: /root/ros2_ws
